version: "3.8"

services:
  hass-proxy:
    build: ./
    ports:
      - "${PORT:-3333}:${PORT:-3333}"
    env_file:
      - .env
    volumes:
      - ./services.yaml:/services.yaml
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping", "|", "grep", "PONG"]
      start_period: 10s
      start_interval: 3s
      interval: 30s
      timeout: 5s
      retries: 3
